# Questions 3.1 to 3.4

### Imports

In [1]:
import config as cfg
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import src.loading as ld
import src.features as ftrs
import src.normalise as norm

### Loading Full DataSet

In [2]:
full_df = ld.load_frames(include_tests=True)

### Normalising Data

In [3]:
full_df_n = norm.normalise_d(full_df)

### Splitting Train/Test

In [4]:
train_df_n = full_df_n[full_df_n["is_test"] == False]
test_df_n = full_df_n[full_df_n["is_test"] == True]

## 3.1

### Feature Table Train

In [ ]:
train_table = ftrs.build_feature_table(train_df_n)

n_missing = train_table.isna().sum().sum()
print(f"Number of missing values in train table: {n_missing}" if n_missing > 0 else "There are no missing values")
train_table

There are no missing values

,M1_mean,M1_std,M1_range,M1_vel,M1_energy,M2_mean,M2_std,M2_range,M2_vel,M2_energy,...,M5_mean,M5_std,M5_range,M5_vel,M5_energy,M6_mean,M6_std,M6_range,M6_vel,M6_energy
video_id,,,,,,,,,,,,,,,,,,,,,
01-01-01-01-01-01-02,0.045541,0.042781,0.166364,0.007619,0.000202,0.572101,0.015992,0.092406,0.004377,0.000064,...,0.092409,0.007922,0.049472,0.001328,8.053063e-06,0.342073,0.005437,0.022040,0.001833,0.000006
01-01-01-01-01-01-03,0.044769,0.030293,0.120792,0.006470,0.000131,0.618272,0.021215,0.088479,0.006103,0.000098,...,0.080128,0.007996,0.048516,0.001620,8.514657e-06,0.296596,0.003172,0.012171,0.001249,0.000003
01-01-01-01-01-01-04,0.046652,0.044842,0.216453,0.007799,0.000282,0.629438,0.028067,0.166719,0.006667,0.000127,...,0.085700,0.011646,0.036762,0.003566,3.272787e-05,0.324766,0.006131,0.033200,0.002677,0.000019
01-01-01-01-01-01-05,0.038562,0.022888,0.086473,0.004317,0.000055,0.616243,0.012968,0.050438,0.002434,0.000013,...,0.083429,0.002401,0.007682,0.000429,3.332948e-07,0.295188,0.005652,0.021534,0.001200,0.000002
01-01-01-01-01-01-06,0.093865,0.059531,0.254196,0.010456,0.000488,0.614809,0.030068,0.164469,0.007354,0.000262,...,0.088501,0.004376,0.030590,0.002017,1.245354e-05,0.314439,0.006173,0.027514,0.001800,0.000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01-01-08-02-02-02-19,0.099246,0.028922,0.166773,0.008806,0.000211,0.587483,0.040577,0.164257,0.007240,0.000198,...,0.053273,0.009961,0.029719,0.001330,5.405914e-06,0.322680,0.012178,0.056924,0.002727,0.000014
01-01-08-02-02-02-20,0.051768,0.031860,0.104523,0.004976,0.000103,0.633839,0.039380,0.108045,0.004447,0.000043,...,0.086016,0.019349,0.070270,0.003650,6.548186e-05,0.304278,0.008732,0.046832,0.003599,0.000040
01-01-08-02-02-02-21,0.148165,0.057097,0.269216,0.015000,0.000697,0.575554,0.054309,0.227479,0.011514,0.000292,...,0.094827,0.004638,0.018004,0.000861,1.352584e-06,0.363545,0.012019,0.045532,0.002319,0.000011
01-01-08-02-02-02-22,0.073067,0.033988,0.136747,0.007584,0.000175,0.572409,0.024289,0.116161,0.006825,0.000099,...,0.072136,0.015007,0.064642,0.003207,4.073242e-05,0.341385,0.022206,0.090212,0.004839,0.000051
01-01-08-02-02-02-23,0.033270,0.030476,0.111538,0.006106,0.000133,0.641111,0.019137,0.083263,0.005891,0.000081,...,0.090398,0.016706,0.083576,0.003729,6.560004e-05,0.362554,0.010312,0.039185,0.003229,0.000021

With the shape of the train feature table, we can see that all 30 features, 5 per measure, have been extracted for each 1200 training videos. We've also checked for missing values and there are none.

### Feature Table Test

In [6]:
test_table = ftrs.build_feature_table(test_df_n)

n_missing_test = test_table.isna().sum().sum()
print(f"Number of missing values in test table: {n_missing_test}" if n_missing_test > 0 else "There are no missing values")
test_table

There are no missing values

,M1_mean,M1_std,M1_range,M1_vel,M1_energy,M2_mean,M2_std,M2_range,M2_vel,M2_energy,...,M5_mean,M5_std,M5_range,M5_vel,M5_energy,M6_mean,M6_std,M6_range,M6_vel,M6_energy
video_id,,,,,,,,,,,,,,,,,,,,,
01-01-01-01-01-01-01,0.028165,0.022060,0.073449,0.004131,0.000066,0.655573,0.016219,0.069935,0.003802,0.000034,...,0.066407,0.009466,0.036429,0.001773,0.000012,0.323191,0.003788,0.024637,0.001803,0.000008
01-01-01-01-01-01-16,0.029068,0.031322,0.152398,0.007709,0.000199,0.586323,0.051559,0.233689,0.010790,0.000336,...,0.084719,0.016148,0.061396,0.002939,0.000036,0.358113,0.003496,0.021052,0.001751,0.000005
01-01-01-01-01-01-17,0.019585,0.021882,0.101151,0.004395,0.000087,0.589827,0.012634,0.051083,0.002694,0.000016,...,0.066463,0.006276,0.040398,0.000893,0.000006,0.321522,0.003431,0.027241,0.001879,0.000007
01-01-01-01-01-01-24,0.052379,0.056067,0.235827,0.008964,0.000295,0.610729,0.035576,0.226121,0.008111,0.000159,...,0.101759,0.005328,0.018317,0.001093,0.000004,0.390799,0.004926,0.021257,0.001432,0.000004
01-01-01-01-01-02-01,0.028854,0.022965,0.074607,0.004479,0.000079,0.669183,0.021994,0.084142,0.003930,0.000042,...,0.063881,0.008055,0.033634,0.001513,0.000009,0.325779,0.003216,0.019791,0.001577,0.000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01-01-08-02-02-01-24,0.078015,0.058940,0.310648,0.013103,0.000511,0.592495,0.046787,0.227592,0.010049,0.000307,...,0.106138,0.015291,0.081837,0.002399,0.000023,0.392080,0.011175,0.054307,0.003145,0.000019
01-01-08-02-02-02-01,0.058803,0.022131,0.089118,0.005702,0.000118,0.619880,0.037623,0.155617,0.006409,0.000118,...,0.086364,0.007073,0.028320,0.000840,0.000002,0.335656,0.005774,0.028674,0.001688,0.000005
01-01-08-02-02-02-16,0.049400,0.032105,0.127913,0.005777,0.000091,0.698400,0.055990,0.235010,0.008246,0.000160,...,0.070965,0.006964,0.043955,0.002006,0.000015,0.321297,0.017484,0.068119,0.003023,0.000015
01-01-08-02-02-02-17,0.052084,0.035576,0.171753,0.009602,0.000269,0.555196,0.054993,0.289116,0.011377,0.000399,...,0.075659,0.012262,0.075561,0.002255,0.000024,0.323450,0.017513,0.074970,0.004909,0.000050
01-01-08-02-02-02-24,0.108972,0.060784,0.367009,0.012760,0.000568,0.647718,0.074115,0.339833,0.011536,0.000425,...,0.100631,0.003291,0.014798,0.000879,0.000001,0.379853,0.014921,0.058277,0.002724,0.000013

As expected, the test feature table has the same number of features as the train feature table, but with 240 rows instead of 1200, the 4 test actors. Again, there are no missing values.